const PRODUCTS = {
    'prod_0': { id: 'prod_0', name: 'Sugarbaby', price: 899.0, image: 'images/products/prod_0.png' },
    'prod_1': { id: 'prod_1', name: 'Latex Bunny Roleplay Set', price: 1199.0, image: 'images/products/prod_1.jpg' },
    'prod_2': { id: 'prod_2', name: 'Bridal theme Lace Set', price: 999.0, image: 'images/products/prod_2.jpg' },
    'prod_3': { id: 'prod_3', name: 'Dominatrix Harness Dress (Stocking incl)', price: 999.0, image: 'images/products/prod_3.jpg' },
    'prod_4': { id: 'prod_4', name: 'Desert Fantasy Set', price: 999.0, image: 'images/products/prod_4.jpg' },
    'prod_5': { id: 'prod_5', name: 'Pikachu Cosplay Bodysuit', price: 749.0, image: 'images/products/prod_5.jpg' },
    'prod_6': { id: 'prod_6', name: 'cat roleplay fantasy Full set with Headgear', price: 999.0, image: 'images/products/prod_6.jpg' },
    'prod_7': { id: 'prod_7', name: 'Dark Web Cosplay Bodysuit (stockings included)', price: 999.0, image: 'images/products/prod_7.jpg' },
    'prod_8': { id: 'prod_8', name: 'Hot Muse Lace Fantasy Set', price: 899.0, image: 'images/products/prod_8.jpg' },
    'prod_9': { id: 'prod_9', name: 'Afterparty Pearl Shirt', price: 999.0, image: 'images/products/prod_9.jpg' },
    'prod_10': { id: 'prod_10', name: 'Leopard Baddie Bodysuit+Belt', price: 949.0, image: 'images/products/prod_10.jpg' },
    'prod_11': { id: 'prod_11', name: 'Babygirl Lingerie set with gloves', price: 899.0, image: 'images/products/prod_11.jpg' },
    'prod_12': { id: 'prod_12', name: 'Date Night Sparkling Bodystocking full', price: 849.0, image: 'images/products/prod_12.png' },
    'prod_13': { id: 'prod_13', name: 'Bunny Velvet Roleplay', price: 1199.0, image: 'images/products/prod_13.jpg' },
    'prod_14': { id: 'prod_14', name: 'Rainbow Babie', price: 849.0, image: 'images/products/prod_14.png' },
    'prod_15': { id: 'prod_15', name: 'Bubblegum Baddie', price: 949.0, image: 'images/products/prod_15.png' },
    'prod_16': { id: 'prod_16', name: 'Bridal Roleplay Dress', price: 999.0, image: 'images/products/prod_16.jpg' },
    'prod_17': { id: 'prod_17', name: 'Latex Main Character Jacket', price: 1199.0, image: 'images/products/prod_17.jpg' },
    'prod_18': { id: 'prod_18', name: 'Shadow Queen Set', price: 799.0, image: 'images/products/prod_18.png' },
    'prod_19': { id: 'prod_19', name: 'Leopard Tease Stocking Set (4pc)', price: 999.0, image: 'images/products/prod_19.jpg' },
    'prod_20': { id: 'prod_20', name: 'Black flow Long lace lingerie', price: 799.0, image: 'images/products/prod_20.jpg' },
    'prod_21': { id: 'prod_21', name: 'Knotty Night Set', price: 749.0, image: 'images/products/prod_21.png' },
    'prod_22': { id: 'prod_22', name: 'Latex Gold Leash set', price: 899.0, image: 'images/products/prod_22.png' },
    'prod_23': { id: 'prod_23', name: 'The Forbidden Dress', price: 799.0, image: 'images/products/prod_23.jpg' },
    'prod_24': { id: 'prod_24', name: 'Baddie Garter Set & Bodysuit', price: 749.0, image: 'images/products/prod_24.jpg' },
    'prod_25': { id: 'prod_25', name: 'Cheetah Print Garter Set', price: 999.0, image: 'images/products/prod_25.jpg' },
    'prod_26': { id: 'prod_26', name: 'Wifey After Dark Set', price: 799.0, image: 'images/products/prod_26.jpg' },
    'prod_27': { id: 'prod_27', name: 'Good Girl Lace Roleplay', price: 949.0, image: 'images/products/prod_27.png' },
    'prod_28': { id: 'prod_28', name: 'Latex Baddie Nurse Roleplay', price: 1499.0, image: 'images/products/prod_28.png' },
    'prod_29': { id: 'prod_29', name: 'Black rhinestone Lingerie', price: 749.0, image: 'images/products/prod_29.jpg' },
    'prod_30': { id: 'prod_30', name: 'Maid Purple Roleplay Fantasy Full Set', price: 999.0, image: 'images/products/prod_30.png' },
    'prod_31': { id: 'prod_31', name: 'Crystal Mesh Bodysuit', price: 849.0, image: 'images/products/prod_31.png' },
    'prod_32': { id: 'prod_32', name: 'Skin Tease Bodysuit', price: 999.0, image: 'images/products/prod_32.jpg' },
    'prod_33': { id: 'prod_33', name: 'Pink Bunny roleplay full set', price: 1499.0, image: 'images/products/prod_33.jpg' },
    'prod_34': { id: 'prod_34', name: 'Honeybun', price: 999.0, image: 'images/products/prod_34.jpg' },
    'prod_35': { id: 'prod_35', name: 'Latex Curve-Fit Bodysuit', price: 949.0, image: 'images/products/prod_35.jpg' },
    'prod_36': { id: 'prod_36', name: 'High voltage Bodysuit', price: 899.0, image: 'images/products/prod_36.jpg' },
    'prod_37': { id: 'prod_37', name: 'Latex Deep Cut Lingerie+stocking', price: 999.0, image: 'images/products/prod_37.jpg' },
    'prod_38': { id: 'prod_38', name: 'RIPPED Bodystocking', price: 599.0, image: 'images/products/prod_38.png' },
    'prod_39': { id: 'prod_39', name: 'Love Lace Babydoll', price: 599.0, image: 'images/products/prod_39.jpg' },
};
